"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wait = exports.Quaternion = exports.Size = exports.Maths = exports.Color = exports.Point = exports.Crypto = exports.PointF = exports.LiteEvent = exports.String = exports.Vector3 = void 0;
var Vector3_1 = require("./Vector3");
Object.defineProperty(exports, "Vector3", { enumerable: true, get: function () { return Vector3_1.Vector3; } });
var String_1 = require("./String");
Object.defineProperty(exports, "String", { enumerable: true, get: function () { return String_1.String; } });
var LiteEvent_1 = require("./LiteEvent");
Object.defineProperty(exports, "LiteEvent", { enumerable: true, get: function () { return LiteEvent_1.LiteEvent; } });
var PointF_1 = require("./PointF");
Object.defineProperty(exports, "PointF", { enumerable: true, get: function () { return PointF_1.PointF; } });
var Crypto_1 = require("./Crypto");
Object.defineProperty(exports, "Crypto", { enumerable: true, get: function () { return Crypto_1.Crypto; } });
var Point_1 = require("./Point");
Object.defineProperty(exports, "Point", { enumerable: true, get: function () { return Point_1.Point; } });
var Color_1 = require("./Color");
Object.defineProperty(exports, "Color", { enumerable: true, get: function () { return Color_1.Color; } });
var Maths_1 = require("./Maths");
Object.defineProperty(exports, "Maths", { enumerable: true, get: function () { return Maths_1.Maths; } });
var Size_1 = require("./Size");
Object.defineProperty(exports, "Size", { enumerable: true, get: function () { return Size_1.Size; } });
var Quaternion_1 = require("./Quaternion");
Object.defineProperty(exports, "Quaternion", { enumerable: true, get: function () { return Quaternion_1.Quaternion; } });
const Wait = (milliseconds) => new Promise(resolve => setTimeout(resolve, milliseconds));
exports.Wait = Wait;
